1주차미션_챈
UMC-MJU-3RD/Server_B pull request #4
Opened 2022-11-06 12:44 UTC by bluesun147

1주차미션_챈

2022-11-06 15:28 UTC, daily1313 commented
Dto로 데이터 감싸서 보내는거 되게 좋은거 같아요. 코드 잘 봤습니다.

2022-11-07 08:38 UTC, sojungpp requested changes
기능 진짜 많이 구현하신 것 같아요👏 그런데 DB 정보는 혹시나 누가 해킹할 수도 있으니까^_^,, gitignore에 넣어서 pr 다시 날려주세요! (+erd도 넣어주세요!)

2022-11-07 16:19 UTC, daily1313 approved these changes
Dto로 데이터 감싸서 보내는거 좋은거 같아요. 코드 잘 봤습니다.

2022-11-08 05:00 UTC, sojungpp approved these changes

2022-11-08 05:01 UTC, merged