6주차미션_왁
UMC-MJU-3RD/Server_B pull request #9
Opened 2022-11-07 04:38 UTC by weejinyoung

-서브모듈 문제 해결
-게시판 프로젝트

2022-11-07 08:52 UTC, sojungpp requested changes
인스타그램에서 필요로 하는 CRUD 위주로 깔끔하게 작성하신 것 같아요👍 DB 정보는 혹시나 해킹당할 수 있으니까^_^,, .gitignore에 넣어서 다시 pr 날려주세요! (+erd도 업로드 부탁드려요)

2022-11-07 15:02 UTC, devryyeong reviewed
JPA 많이 배워갑니다👍 근데 domain이랑 dto는 보통 구분하는게 국룰인가요 아니면 취향차이인가요 그리고 각각 역할도 궁금해요 (스프링..쏘 디피컬트

2022-11-07 15:47 UTC, weejinyoung commented
https://tecoble.techcourse.co.kr/post/2020-08-31-dto-vs-entity/

잘 설명되어 있는 포스팅 주소 하나 보내드립니다

dto가 없어도 틀린 설계는 아니지만, dto를 만드는 이유는 여러가지가 있습니다

나령님은 프론트엔드에서 잔뼈가 굵으신 분이니 프론트랑 연관해서 하나 말씀 드려보자면

프론트가 백에게서 특정 회원의 이름과 나이만 받고싶어 요청을 보냈다고 가정 해보겠습니다

이때 백이 응답으로 해당 회원 엔티티를 응답으로 보내면

해당 회원 엔티티에 있는 모든 정보가 보내지겠죠

프론트는 회원의 이름과 나이만 받고 싶었지만 필요없는 모든 정보를 받게되는겁니다

이때 회원의 이름과 나이만 있는 dto를 만들어서 보내면 프론트가 편해지겠죠?

이것 또한 프론트의 입장에서 dto가 있으면 좋은 여러가지 이유 중 하나일 뿐입니다

제가 생각하는 dto가 필요한 가장 큰 이유는

하나의 클래스가 하나의 역할을 가진다는 객체지향의 룰을 지키기 위함이라고 생각합니다

엔티티 클래스는 서비스 도메인이라는 역할만 수행할 수 있게 클라이언트, 서버 간 정보 전송의 역할은 dto라는 클래스로 구현해주는 것이죠

짧고 비루한 공력이지만 주제넘게 제 생각을 말씀드려보자면

객체지향적 설계의 개념이 탄탄하게 뒷받침 되어야 스프링을 이해할 수 있고 스프링을 더 잘 사용할 수 있다고 생각합니다

"객체지향의 사실과 오해"라는 책을 추천합니다 전 아주 많이많이 도움이 됐거든요ㅎㅎ

어지러운 세미나 커리큘럼 때문에 고생 많으시죠, 그럼에도 최선을 다해 열심히 공부하시는 모습이 멋있습니다

앞으로 제것도 냉철한 코드리뷰 부탁드리겠습니다 서로 힘이 되어보아요


2022년 11월 8일 (화) 오전 12:03, Na Ryeong Lee ***@***.***>님이 작성:

> ***@***.**** commented on this pull request.
>
> JPA 많이 배워갑니다👍 근데 domain이랑 dto는 보통 구분하는게 국룰인가요 아니면 취향차이인가요 그리고 각각 역할도
> 궁금해요 (스프링..쏘 디피컬트
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/UMC-MJU-3RD/Server_B/pull/9#pullrequestreview-1170562271>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AVVN72ER57U2CHGOVB2VYJDWHEK2LANCNFSM6AAAAAARYZIMDA>
> .
> You are receiving this because you were assigned.Message ID:
> ***@***.***>
>

2022-11-07 16:20 UTC, devryyeong approved these changes
다 객체지향과 관련된 심오한 이유가 있었군요 자세히 알려주셔서 감사합니다 링크도 도움 많이 되었어요 bb

2022-11-08 05:00 UTC, sojungpp approved these changes

2022-11-08 05:00 UTC, merged